version: "3.8"

services:

# databases
  keycloak-db:
    container_name: keycloak-db
    image: postgres:14-alpine
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # backends
  keycloak:
    container_name: keycloak
    build: .
    expose:
      - "80"
    command:
      - "start-dev"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  # frontends
  landing-page:
    container_name: landing-page
    image: ghcr.io/gamify-it/landing-page:main
    restart: always
    pull_policy: always
    expose:
      - "80"

  # reverse-proxy
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./.nginx/compose/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # ports:
    #   - "80:80"
